### ISSUE TITLE
Getting this library to v 1.0

### ISSUE THREAD

**Issue by skatkov** [cheddar-me/pbbuilder#15]
This library has been in use on production almost unchanged for what seems to be close to 2 years. And went through most complicated test of them all - test of time. And it looks to me, that it already deserves more mature version number, one that doesn't start with 0.* :)

As I see, that biggest issue right now is that README  is empty - #7

Is there anything else, that needs to be resolved before we can call this a stable 1.0 release?

**Comment by jujustayfly** [comment]
It is definitely missing some instructions yes. Also we have been playing around with caching lately which could maybe have an impact on this repo. 🤷‍♀️

**Comment by skatkov** [comment]
I have created a milestone with all the issues that we need to resolve to get to v1.

https://github.com/cheddar-me/pbbuilder/milestone/1

Please feel free to propose additional tasks, if you feel that anything is missing.
